// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: warehouse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Leading.Services {

  /// <summary>Holder for reflection information generated from warehouse.proto</summary>
  public static partial class WarehouseReflection {

    #region Descriptor
    /// <summary>File descriptor for warehouse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WarehouseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg93YXJlaG91c2UucHJvdG8SEExlYWRpbmcuU2VydmljZXMibwobQWRkQnJh",
            "bmNoVG9XYXJlaG91c2VSZXF1ZXN0EhAKCGJyYW5jaElkGAEgASgFEhIKCmJy",
            "YW5jaFJhbmsYAiABKAkSEwoLd2FyZWhvdXNlSWQYAyABKAUSFQoNd2FyZWhv",
            "dXNlVHlwZRgEIAEoBSIeChxBZGRCcmFuY2hUb1dhcmVob3VzZVJlc3BvbnNl",
            "MokBChBXYXJlaG91c2VTZXJ2aWNlEnUKFEFkZEJyYW5jaFRvV2FyZWhvdXNl",
            "Ei0uTGVhZGluZy5TZXJ2aWNlcy5BZGRCcmFuY2hUb1dhcmVob3VzZVJlcXVl",
            "c3QaLi5MZWFkaW5nLlNlcnZpY2VzLkFkZEJyYW5jaFRvV2FyZWhvdXNlUmVz",
            "cG9uc2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Leading.Services.AddBranchToWarehouseRequest), global::Leading.Services.AddBranchToWarehouseRequest.Parser, new[]{ "BranchId", "BranchRank", "WarehouseId", "WarehouseType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Leading.Services.AddBranchToWarehouseResponse), global::Leading.Services.AddBranchToWarehouseResponse.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AddBranchToWarehouseRequest : pb::IMessage<AddBranchToWarehouseRequest> {
    private static readonly pb::MessageParser<AddBranchToWarehouseRequest> _parser = new pb::MessageParser<AddBranchToWarehouseRequest>(() => new AddBranchToWarehouseRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddBranchToWarehouseRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Leading.Services.WarehouseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddBranchToWarehouseRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddBranchToWarehouseRequest(AddBranchToWarehouseRequest other) : this() {
      branchId_ = other.branchId_;
      branchRank_ = other.branchRank_;
      warehouseId_ = other.warehouseId_;
      warehouseType_ = other.warehouseType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddBranchToWarehouseRequest Clone() {
      return new AddBranchToWarehouseRequest(this);
    }

    /// <summary>Field number for the "branchId" field.</summary>
    public const int BranchIdFieldNumber = 1;
    private int branchId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BranchId {
      get { return branchId_; }
      set {
        branchId_ = value;
      }
    }

    /// <summary>Field number for the "branchRank" field.</summary>
    public const int BranchRankFieldNumber = 2;
    private string branchRank_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BranchRank {
      get { return branchRank_; }
      set {
        branchRank_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "warehouseId" field.</summary>
    public const int WarehouseIdFieldNumber = 3;
    private int warehouseId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WarehouseId {
      get { return warehouseId_; }
      set {
        warehouseId_ = value;
      }
    }

    /// <summary>Field number for the "warehouseType" field.</summary>
    public const int WarehouseTypeFieldNumber = 4;
    private int warehouseType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WarehouseType {
      get { return warehouseType_; }
      set {
        warehouseType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddBranchToWarehouseRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddBranchToWarehouseRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BranchId != other.BranchId) return false;
      if (BranchRank != other.BranchRank) return false;
      if (WarehouseId != other.WarehouseId) return false;
      if (WarehouseType != other.WarehouseType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BranchId != 0) hash ^= BranchId.GetHashCode();
      if (BranchRank.Length != 0) hash ^= BranchRank.GetHashCode();
      if (WarehouseId != 0) hash ^= WarehouseId.GetHashCode();
      if (WarehouseType != 0) hash ^= WarehouseType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BranchId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BranchId);
      }
      if (BranchRank.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BranchRank);
      }
      if (WarehouseId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(WarehouseId);
      }
      if (WarehouseType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(WarehouseType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BranchId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BranchId);
      }
      if (BranchRank.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BranchRank);
      }
      if (WarehouseId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WarehouseId);
      }
      if (WarehouseType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WarehouseType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddBranchToWarehouseRequest other) {
      if (other == null) {
        return;
      }
      if (other.BranchId != 0) {
        BranchId = other.BranchId;
      }
      if (other.BranchRank.Length != 0) {
        BranchRank = other.BranchRank;
      }
      if (other.WarehouseId != 0) {
        WarehouseId = other.WarehouseId;
      }
      if (other.WarehouseType != 0) {
        WarehouseType = other.WarehouseType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BranchId = input.ReadInt32();
            break;
          }
          case 18: {
            BranchRank = input.ReadString();
            break;
          }
          case 24: {
            WarehouseId = input.ReadInt32();
            break;
          }
          case 32: {
            WarehouseType = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AddBranchToWarehouseResponse : pb::IMessage<AddBranchToWarehouseResponse> {
    private static readonly pb::MessageParser<AddBranchToWarehouseResponse> _parser = new pb::MessageParser<AddBranchToWarehouseResponse>(() => new AddBranchToWarehouseResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddBranchToWarehouseResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Leading.Services.WarehouseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddBranchToWarehouseResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddBranchToWarehouseResponse(AddBranchToWarehouseResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddBranchToWarehouseResponse Clone() {
      return new AddBranchToWarehouseResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddBranchToWarehouseResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddBranchToWarehouseResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddBranchToWarehouseResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
