// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: warehouse.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Leading.Services {
  public static partial class WarehouseService
  {
    static readonly string __ServiceName = "Leading.Services.WarehouseService";

    static readonly grpc::Marshaller<global::Leading.Services.AddBranchToWarehouseRequest> __Marshaller_AddBranchToWarehouseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Leading.Services.AddBranchToWarehouseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Leading.Services.AddBranchToWarehouseResponse> __Marshaller_AddBranchToWarehouseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Leading.Services.AddBranchToWarehouseResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Leading.Services.AddBranchToWarehouseRequest, global::Leading.Services.AddBranchToWarehouseResponse> __Method_AddBranchToWarehouse = new grpc::Method<global::Leading.Services.AddBranchToWarehouseRequest, global::Leading.Services.AddBranchToWarehouseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddBranchToWarehouse",
        __Marshaller_AddBranchToWarehouseRequest,
        __Marshaller_AddBranchToWarehouseResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Leading.Services.WarehouseReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WarehouseService</summary>
    public abstract partial class WarehouseServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Leading.Services.AddBranchToWarehouseResponse> AddBranchToWarehouse(global::Leading.Services.AddBranchToWarehouseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WarehouseService</summary>
    public partial class WarehouseServiceClient : grpc::ClientBase<WarehouseServiceClient>
    {
      /// <summary>Creates a new client for WarehouseService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WarehouseServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WarehouseService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WarehouseServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WarehouseServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WarehouseServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Leading.Services.AddBranchToWarehouseResponse AddBranchToWarehouse(global::Leading.Services.AddBranchToWarehouseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddBranchToWarehouse(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Leading.Services.AddBranchToWarehouseResponse AddBranchToWarehouse(global::Leading.Services.AddBranchToWarehouseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddBranchToWarehouse, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Leading.Services.AddBranchToWarehouseResponse> AddBranchToWarehouseAsync(global::Leading.Services.AddBranchToWarehouseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddBranchToWarehouseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Leading.Services.AddBranchToWarehouseResponse> AddBranchToWarehouseAsync(global::Leading.Services.AddBranchToWarehouseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddBranchToWarehouse, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WarehouseServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WarehouseServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(WarehouseServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddBranchToWarehouse, serviceImpl.AddBranchToWarehouse).Build();
    }

  }
}
#endregion
